require File.dirname(__FILE__) + '/disney_base'
require File.dirname(__FILE__) + '/disney_resort'
require File.dirname(__FILE__) + '/disney_attraction'
require File.dirname(__FILE__) + '/disney_world'
require File.dirname(__FILE__) + '/disneyland'
require File.dirname(__FILE__) + '/disneyland_paris'
require File.dirname(__FILE__) + '/hong_kong_disneyland'